#!/bin/bash
#basket = ~/RECYCLE

#RENAME  = $(date  +%y%m%d)

if [ -e ~/RECYCLE ] 
then 
	mv "$1" ~/RECYCLE
else
	mkdir ~/RECYCLE 
	mv "$1" ~/RECYCLE
fi
#echo 'Файл '$1' перемещен успешно'

if [ -e ~/RECYCLE/"$1" ]
then
	cd ~/RECYCLE
	gzip "$1"
	echo "файл был архивирован"
else 
	"Файл не был архивирован" 
fi 

if [ -e ~/RECYCLE/"$1".gz ]
then 
#	echo "exist this file"
	mv "$1".gz "$1":$(date +% d-%m-%y).gz
fi

if [ -e ~/RECYCLE ] 
then 
	cd ~/RECYCLE
	find . -name "*.gz"
fi
