#!/bin/bash
#Данный скрип позволяет удалять выбранный файл 
# пример команды srm namefle

if [ -e ~/RECYCLE ] 
then 
	mv "$1" ~/RECYCLE
else
	mkdir ~/RECYCLE 
	mv "$1" ~/RECYCLE
fi

if [ -e ~/RECYCLE/"$1" ]
then
	cd ~/RECYCLE
	gzip "$1"
	echo "файл был успешно удален"
else 
	"Файл не был удален" 
fi 

if [ -e ~/RECYCLE/"$1".gz ]
then 
#	echo "exist this file"
	mv "$1".gz "$1":$(date +%F,%T).gz
fi

if [ -e ~/RECYCLE ] 
then 
	cd ~/RECYCLE
	find -mtime 7 -name "*.gz" -delete
fi
